### ISSUE TITLE
Add a "try out" mode for testing (or make it more clear, that the live data is edited)

### ISSUE THREAD

**Issue by tordans** [meta-systems/openrecyclemap#10]
I tried to test the map and it was not fully clear for me, that the live data was being edited right away. 

I reverted my change afterwards https://www.openstreetmap.org/node/3026682702/history

I think two thinks could help here:
- add a try out mode that uses the dev-version of the osm-database
- change the wording on the edit page/save page, to make it more clear that live data is being edited

ps: This tool looks very promising!

**Comment by tordans** [comment]
Just for reference, so I may find it again some day :).

> **tordans 10:23 Uhr**
Is there a overpass-instance that is based on api06.dev.openstreetmap.org? UseCase: Single purpose editors like https://github.com/meta-systems/openrecyclemap/issues/10 need two parts to create a sandbox experience, the dev-api and the overpass api to query results. Is there such a setup somewhere?
**### 14:25 Uhr**
@tordans: unfortunately that's not feasible at the moment. There's no minutely diff job running on the dev instance, which would be a prerequisite for an Overpass instance to consume changes.

**Comment by petrovnn** [comment]
It may be necessary to make a list of points added by the user?

Such a list would help control the purity of the data sent to the osm production database.

**Comment by vitalcrazz** [comment]
I added a test mode in 8ffebaa9043726d53574690b4f87760e9cc637f4

Now when you run `npm run serve` the app uses an osm dev server.
And when you run `npm run build` the app uses a production server.

But there are some problems:
- you need a separate account to sign in osm dev server
- you can't edit most of the data because the dev server is very outdated
